#!/bin/sh

#-------------------------------------------------------------------------------
# Name:        EndOfOil_clear_folders.sh
# Purpose:     Delete contents of downstream folders before running all code
#	       Copy images into output/figures that are not generated by
#	       code but are part of paper
#
# Created:     8 November, 2024
#-------------------------------------------------------------------------------

# Script relies on $REPODIR and $DBDIR variables exported from EndOfOil_bash_file.sh

# DELETE ALL INTERMEDIATE DATA FILES IN DROPBOX
find "$DBDIR/intermediatefiles" -type f -delete

# DELETE ALL FIGURES, TABLES, AND SINGLE NUM TEX FILES STORED IN REPO RESULTS
find "$REPODIR/output/" -type f -delete

# DELETE COMPILED PAPER
rm "$REPODIR/paper/EndOfOil.pdf"
rm "$REPODIR/paper/EndOfOil_appx.pdf"

# COPY IMAGES FROM DROPBOX TO REPO
cp "$DBDIR/CartoonFigures/ThyFigA.png" "$REPODIR/output/figures"
cp "$DBDIR/CartoonFigures/ThyFigB.png" "$REPODIR/output/figures"

# Clean up log files
rm *.log

exit
